/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.d2s2.spade.view.item;

import com.d2s2.spade.controllers.item.BrandController;
import com.d2s2.spade.controllers.item.CutterController;
import com.d2s2.spade.controllers.item.ItemCategoryController;
import com.d2s2.spade.controllers.item.ItemController;
import com.d2s2.spade.controllers.item.KiyathController;
import com.d2s2.spade.controllers.item.PlanerBladeController;
import com.d2s2.spade.controllers.item.RouterCutterController;
import com.d2s2.spade.controllers.item.SilverSoleController;
import com.d2s2.spade.controllers.item.TipController;
import com.d2s2.spade.controllers.item.WheelController;
import com.d2s2.spade.controllers.supplier.SupplierController;
import com.d2s2.spade.models.Brand;
import com.d2s2.spade.models.Cutter;
import com.d2s2.spade.models.Item;
import com.d2s2.spade.models.ItemCategory;
import com.d2s2.spade.models.Kiyath;
import com.d2s2.spade.models.PlanerBlade;
import com.d2s2.spade.models.RouterCutter;
import com.d2s2.spade.models.SilverSole;
import com.d2s2.spade.models.Supplier;
import com.d2s2.spade.models.Tip;
import com.d2s2.spade.models.Wheel;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Heshan Sandamal
 */
public class ViewItemForm extends javax.swing.JDialog {

    private DefaultTableModel dtm;
    private ArrayList<Item> allItems;
    /**
     * Creates new form ViewItemForm
     */
    private TableRowSorter<TableModel> sorter;
    private final DefaultTableModel dtmForItemDetailTable;

    public ViewItemForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setSize(Toolkit.getDefaultToolkit().getScreenSize());

        dtmForItemDetailTable = (DefaultTableModel) itemDetailTable.getModel();

        try {
            getAllItemDetails();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }


        setTableSorter();

        setSortKeys();

        setCancelActionToSearchTextField();

        keywordSerachRadioButton.setSelected(true);
        keywordSearch();



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        advancedSearchButton = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jXTable3 = new org.jdesktop.swingx.JXTable();
        itemPane = new javax.swing.JScrollPane();
        itemTable = new org.jdesktop.swingx.JXTable();
        advanceSearchPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        itemCategoryCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        brandCombo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        supplierCombo = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        salesTypeCombo1 = new javax.swing.JComboBox();
        itemCategoryCheckBox = new javax.swing.JCheckBox();
        saleTypeCheckBox = new javax.swing.JCheckBox();
        brandCheckBox = new javax.swing.JCheckBox();
        supplierCheckBox = new javax.swing.JCheckBox();
        searchAdvanceButton = new javax.swing.JButton();
        keywordSerachRadioButton = new javax.swing.JRadioButton();
        detailPanel = new javax.swing.JScrollPane();
        itemDetailTable = new org.jdesktop.swingx.JXTable();
        jLabel1 = new javax.swing.JLabel();
        keywordSearchPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        searchTextField = new org.jdesktop.swingx.JXSearchField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(advancedSearchButton);
        advancedSearchButton.setText("Advanced Search");
        advancedSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedSearchButtonActionPerformed(evt);
            }
        });

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Batch table"));

        jXTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jXTable3);

        itemPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Table"));

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Category", "Brand", "Supplier", "Supplier Name", "Description"
            }
        ));
        itemTable.setShowGrid(true);
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTableMouseClicked(evt);
            }
        });
        itemTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                itemTablePropertyChange(evt);
            }
        });
        itemTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemTableKeyReleased(evt);
            }
        });
        itemPane.setViewportView(itemTable);

        advanceSearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sort By"));

        jLabel7.setText("Item Category");

        itemCategoryCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        itemCategoryCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemCategoryComboItemStateChanged(evt);
            }
        });
        itemCategoryCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemCategoryComboKeyReleased(evt);
            }
        });

        jLabel9.setText("Brand");

        brandCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        brandCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brandComboItemStateChanged(evt);
            }
        });
        brandCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandComboActionPerformed(evt);
            }
        });

        jLabel10.setText("Supplier");

        supplierCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S-0001" }));

        jLabel12.setText("Sale/Non-Sale");

        salesTypeCombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sale", "Non-Sale" }));

        searchAdvanceButton.setText("SEARCH");
        searchAdvanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdvanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout advanceSearchPanelLayout = new javax.swing.GroupLayout(advanceSearchPanel);
        advanceSearchPanel.setLayout(advanceSearchPanelLayout);
        advanceSearchPanelLayout.setHorizontalGroup(
            advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(itemCategoryCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemCategoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(saleTypeCheckBox))
                    .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(brandCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                        .addComponent(brandCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(searchAdvanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                        .addComponent(salesTypeCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        advanceSearchPanelLayout.setVerticalGroup(
            advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                        .addGroup(advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemCategoryCheckBox)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advanceSearchPanelLayout.createSequentialGroup()
                        .addGroup(advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(itemCategoryCombo))
                            .addComponent(brandCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(brandCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(saleTypeCheckBox)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salesTypeCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(advanceSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(supplierCheckBox)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(supplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(advanceSearchPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(searchAdvanceButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(keywordSerachRadioButton);
        keywordSerachRadioButton.setText("Search by Code");
        keywordSerachRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordSerachRadioButtonActionPerformed(evt);
            }
        });

        detailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Detail Table"));

        itemDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Property", "value"
            }
        ));
        itemDetailTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemDetailTableMouseClicked(evt);
            }
        });
        itemDetailTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemDetailTableKeyPressed(evt);
            }
        });
        detailPanel.setViewportView(itemDetailTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View Item & Batch Details");

        keywordSearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sort By"));

        jLabel5.setText("search text:");

        searchTextField.setEnabled(false);
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        searchTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchTextFieldPropertyChange(evt);
            }
        });
        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout keywordSearchPanelLayout = new javax.swing.GroupLayout(keywordSearchPanel);
        keywordSearchPanel.setLayout(keywordSearchPanelLayout);
        keywordSearchPanelLayout.setHorizontalGroup(
            keywordSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keywordSearchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        keywordSearchPanelLayout.setVerticalGroup(
            keywordSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keywordSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(keywordSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemPane)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keywordSerachRadioButton)
                            .addComponent(keywordSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(advanceSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(advancedSearchButton))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(471, 471, 471))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordSerachRadioButton)
                    .addComponent(advancedSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(advanceSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keywordSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemPane, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane7.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCategoryComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemCategoryComboItemStateChanged
    }//GEN-LAST:event_itemCategoryComboItemStateChanged

    private void itemCategoryComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCategoryComboKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCategoryComboKeyReleased

    private void brandComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brandComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_brandComboItemStateChanged

    private void brandComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandComboActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void searchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyReleased
        String text = searchTextField.getText();

        if (text.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(sorter.getRowFilter().regexFilter("^(?i)" + text));
        }


    }//GEN-LAST:event_searchTextFieldKeyReleased

    private void searchTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchTextFieldPropertyChange
    }//GEN-LAST:event_searchTextFieldPropertyChange

    private void searchAdvanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdvanceButtonActionPerformed

        try {

            ArrayList<RowFilter<Object, Object>> rfs = new ArrayList<RowFilter<Object, Object>>(2);

            if (itemCategoryCheckBox.isSelected()) {
                rfs.add(RowFilter.regexFilter("^(?i)" + itemCategoryCombo.getSelectedItem().toString(), 1));
            }

            if (brandCheckBox.isSelected()) {
                rfs.add(RowFilter.regexFilter("^(?i)" + brandCombo.getSelectedItem().toString(), 2));
            }

            if (supplierCheckBox.isSelected()) {
                rfs.add(RowFilter.regexFilter("^(?i)" + supplierCombo.getSelectedItem().toString(), 4));
            }


            RowFilter<Object, Object> af = RowFilter.andFilter(rfs);


            sorter.setRowFilter(af);
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_searchAdvanceButtonActionPerformed

    private void keywordSerachRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordSerachRadioButtonActionPerformed
        keywordSearch();        // TODO add your handling code here:
    }//GEN-LAST:event_keywordSerachRadioButtonActionPerformed

    private void advancedSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedSearchButtonActionPerformed
        advancedSearch();        // TODO add your handling code here:
    }//GEN-LAST:event_advancedSearchButtonActionPerformed

    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
        try {
            setItemDetails();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemTableMouseClicked

    private void itemDetailTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDetailTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemDetailTableMouseClicked

    private void itemTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemTableKeyPressed
    }//GEN-LAST:event_itemTableKeyPressed

    private void itemDetailTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemDetailTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemDetailTableKeyPressed

    private void itemTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemTableKeyReleased
    }//GEN-LAST:event_itemTableKeyReleased

    private void itemTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_itemTablePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTablePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewItemForm dialog = new ViewItemForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel advanceSearchPanel;
    private javax.swing.JRadioButton advancedSearchButton;
    private javax.swing.JCheckBox brandCheckBox;
    private javax.swing.JComboBox brandCombo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane detailPanel;
    private javax.swing.JCheckBox itemCategoryCheckBox;
    private javax.swing.JComboBox itemCategoryCombo;
    private org.jdesktop.swingx.JXTable itemDetailTable;
    private javax.swing.JScrollPane itemPane;
    private org.jdesktop.swingx.JXTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private org.jdesktop.swingx.JXTable jXTable3;
    private javax.swing.JPanel keywordSearchPanel;
    private javax.swing.JRadioButton keywordSerachRadioButton;
    private javax.swing.JCheckBox saleTypeCheckBox;
    private javax.swing.JComboBox salesTypeCombo1;
    private javax.swing.JButton searchAdvanceButton;
    private org.jdesktop.swingx.JXSearchField searchTextField;
    private javax.swing.JCheckBox supplierCheckBox;
    private javax.swing.JComboBox supplierCombo;
    // End of variables declaration//GEN-END:variables

    //-------------------------------constructor calls---------------------------------------------
    public void getAllItemDetails() throws ClassNotFoundException, SQLException {

        //load table
        allItems = ItemController.getAllItems();




        //load combo boxes
        ArrayList<Brand> brandTypes = BrandController.getAllBrands();
        ArrayList<ItemCategory> itemCategories = ItemCategoryController.getAllItemCategories();
        ArrayList<Supplier> supplierList = SupplierController.getAllSuppliers();


        dtm = (DefaultTableModel) itemTable.getModel();
        dtm.setRowCount(0);


        //for (int i = 0; i < 5000; i++) {



        for (Item item : allItems) {

            String category = null;
            for (ItemCategory itemCategory : itemCategories) {
                if (itemCategory.equals(item.getItemCode())) {
                    category = itemCategory.getCategory();
                }
            }

            String brandType = null;
            for (Brand brand : brandTypes) {
                if (brand.equals(item.getBrandId())) {
                    brandType = brand.getBrand();
                }
            }

            String supplierName = null;
            for (Supplier supplier : supplierList) {
                if (supplier.equals(item.getSupplierId())) {
                    supplierName = supplier.getName();
                }
            }


            dtm.addRow(new Object[]{item.getCode(), category, brandType, item.getSupplierId(), supplierName, item.getSubId()});



        }

        //}//

        supplierCombo.removeAllItems();
        for (Supplier supplier : supplierList) {
            supplierCombo.addItem(supplier.getName());
        }

        brandCombo.removeAllItems();
        for (Brand brand : brandTypes) {
            brandCombo.addItem(brand.getBrand());
        }

        itemCategoryCombo.removeAllItems();
        for (ItemCategory itemCategory : itemCategories) {
            itemCategoryCombo.addItem(itemCategory.getCategory());
        }
    }

    private void setCancelActionToSearchTextField() {
        searchTextField.setCancelAction(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                searchTextField.setText("");
                sorter.setRowFilter(null);
            }
        });
    }

    private void setTableSorter() {
        sorter = new TableRowSorter<>(itemTable.getModel());
        itemTable.setRowSorter(sorter);
    }

    private void setSortKeys() {
        sorter.setComparator(1, new Comparator<String>() {
            @Override
            public int compare(String o1, String o2) {
                return o1.substring(0, Math.min(o1.length(), 5)).compareTo(itemCategoryCombo.getSelectedItem().toString().substring(0, Math.min(o2.length(), 5)));
            }
        });

    }

    private void keywordSearch() {
        if (keywordSerachRadioButton.isSelected()) {
            sorter.setRowFilter(null);
            for (Component component : keywordSearchPanel.getComponents()) {
                component.setEnabled(true);
            }

            for (Component component : advanceSearchPanel.getComponents()) {
                component.setEnabled(false);
            }
        }

    }

    private void advancedSearch() {
        if (advancedSearchButton.isSelected()) {
            searchTextField.setText("");
            sorter.setRowFilter(null);
            for (Component component : keywordSearchPanel.getComponents()) {
                component.setEnabled(false);
            }

            for (Component component : advanceSearchPanel.getComponents()) {
                component.setEnabled(true);
            }
        }

    }

    private void setItemDetails() throws ClassNotFoundException, SQLException {
        if (itemTable.getSelectedRow() != -1) {
            String category = itemTable.getValueAt(itemTable.getSelectedRow(), 1).toString();
            String code = itemTable.getValueAt(itemTable.getSelectedRow(), 0).toString();
            //System.out.println(code);


            if (category.equals(Kiyath.class.getSimpleName())) {
                setKiyathDetails(code);
            } else if (category.equals("Router Cutter")) {
                setRouterCutterDetails(code);
            } else if (category.equals("Silver Sole")) {
                setSilverSoleDetails(code);
            } else if (category.equals("Planer Blade")) {
                setPlanerBladeDetails(code);
            } else if (category.equals("Tip")) {
                setTipDetails(code);
            } else if (category.equals("Cutter")) {
                setCutterDetails(code);
            } else if (category.equals("Wheel")) {
                setWheelDetails(code);
            } else if (category.equals("Plux")) {
                setPluxDetails(code);
            }

        }
    }

    private void setKiyathDetails(String code) throws ClassNotFoundException, SQLException {
        Kiyath detailsOfItem = KiyathController.getDetailsOfItem(code);
        dtmForItemDetailTable.setRowCount(0);
        dtmForItemDetailTable.addRow(new Object[]{"Size: ", detailsOfItem.getSize()});
        dtmForItemDetailTable.addRow(new Object[]{"No of Tips: ", detailsOfItem.getNoOfTips()});

    }

    private void setRouterCutterDetails(String code) throws ClassNotFoundException, SQLException {
        RouterCutter detailsOfItem = RouterCutterController.getDetailsOfItem(code);
        dtmForItemDetailTable.setRowCount(0);
        dtmForItemDetailTable.addRow(new Object[]{"Size: ", detailsOfItem.getSize()});
    }

    private void setSilverSoleDetails(String code) throws ClassNotFoundException, SQLException {
        SilverSole detailsOfItem = SilverSoleController.getDetailsOfItem(code);
        dtmForItemDetailTable.setRowCount(0);
        dtmForItemDetailTable.addRow(new Object[]{"Type : ", detailsOfItem.getType()});
        dtmForItemDetailTable.addRow(new Object[]{"Price : ", detailsOfItem.getPrice()});
    }

    private void setPlanerBladeDetails(String code) throws ClassNotFoundException, SQLException {
        PlanerBlade detailsOfItem = PlanerBladeController.getDetailsOfItem(code);
        dtmForItemDetailTable.setRowCount(0);
        dtmForItemDetailTable.addRow(new Object[]{"Type : ", detailsOfItem.getType()});
        dtmForItemDetailTable.addRow(new Object[]{"size : ", detailsOfItem.getSize()});
    }

    private void setTipDetails(String code) throws ClassNotFoundException, SQLException {
        Tip detailsOfItem = TipController.getDetailsOfItem(code);
        dtmForItemDetailTable.setRowCount(0);
        dtmForItemDetailTable.addRow(new Object[]{"Size : ", detailsOfItem.getSize()});
        dtmForItemDetailTable.addRow(new Object[]{"country : ", detailsOfItem.getCountry()});
        dtmForItemDetailTable.addRow(new Object[]{"price : ", detailsOfItem.getPrice()});
    }

    private void setCutterDetails(String code) throws ClassNotFoundException, SQLException {
        Cutter detailsOfItem = CutterController.getDetailsOfItem(code);
        dtmForItemDetailTable.setRowCount(0);
        dtmForItemDetailTable.addRow(new Object[]{"Size : ", detailsOfItem.getSize()});
        dtmForItemDetailTable.addRow(new Object[]{"No of tips : ", detailsOfItem.getNoOfTips()});
        dtmForItemDetailTable.addRow(new Object[]{"Thickness : ", detailsOfItem.getThickness()});

    }

    private void setWheelDetails(String code) throws ClassNotFoundException, SQLException {
        Wheel detailsOfItem = WheelController.getDetailsOfItem(code);
        dtmForItemDetailTable.setRowCount(0);
        dtmForItemDetailTable.addRow(new Object[]{"SIze : ", detailsOfItem.getSize()});
        dtmForItemDetailTable.addRow(new Object[]{"Country : ", detailsOfItem.getCountry()});
        dtmForItemDetailTable.addRow(new Object[]{"Diameter : ", detailsOfItem.getDiameter()});
        dtmForItemDetailTable.addRow(new Object[]{"Hole : ", detailsOfItem.getHole()});
    }

    private void setPluxDetails(String code) {
        dtmForItemDetailTable.setRowCount(0);
    }
}
